
mt4:
  manager:
    api: ${project.basedir}/static/dll/mtmanapi64.dll
    dll: ${project.basedir}/static/dll/Basic_MT4Wrapper.dll
    ip: 18.166.60.218:2004
#    api: "classpath:*/dll/mtmanapi64.dll"
#    dll: "classpath:/dll/Basic_MT4Wrapper.dll"
#    ip: "18.166.60.218:2004"

